### ISSUE TITLE
process problem

### ISSUE THREAD

**Issue by b4zz4** [jgarzik/pyminer#10]
./pyminer.py example-config.cfg
> ...
> Process Process-4:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "./pyminer.py", line 207, in miner_thread
>     miner.loop()
>   File "./pyminer.py", line 203, in loop
>     self.iterate(rpc)
>   File "./pyminer.py", line 167, in iterate
>     work = rpc.getwork()
>   File "./pyminer.py", line 76, in getwork
>     return self.rpc('getwork', data)
>   File "./pyminer.py", line 56, in rpc
>     resp = self.conn.getresponse()
>   File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
>     response.begin()
>   File "/usr/lib/python2.7/httplib.py", line 415, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
>     raise BadStatusLine(line)
>  BadStatusLine: ''

**Comment by b4zz4** [comment]
close without help?

**Comment by ORP967** [comment]
I have a working miner that uses the current "getworktemplate" in python 3. It is a code from (https://github.com/vsergeev) that I changed to check for a new block every 20 sc or so and start mining again every time a new block is detected. Currently getting 1.01KH/s on a Dell.
