### ISSUE TITLE
Issue:  httplib ``No Module named httplib```

### ISSUE THREAD

**Issue by ctkqiang** [jgarzik/pyminer#20]
https://github.com/jgarzik/pyminer/blob/3740e1a9149fa79e448a31f09300f605457afe83/pyminer.py#L26

To those who have the issue ```    import httplib
ImportError: No module named httplib```, FYI in ```Python 3``` the module renamed to ```http.client```

Read this >>>>>>>>>>>> [The documnetation](https://docs.python.org/3/library/http.client.html)

Hope I did Help anyone <3

**Comment by ORP967** [comment]
I have a working miner that uses the current "getworktemplate" in python 3. It is a code from (https://github.com/vsergeev) that I changed to check for a new block every 20 sc or so and start mining again every time a new block is detected. Currently getting 1.01KH/s on a Dell.
