### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by viraxor** [jgarzik/pyminer#21]
`MAX_NONCE = 1000000L` is the code

**Comment by peace606** [comment]
> 
> 
> `MAX_NONCE = 1000000L` is the code

""

**Comment by wmack20** [comment]
#22

**Comment by Shubhaankar-Sharma** [comment]
you have to run this on python 2

**Comment by appledevpro** [comment]
yea i did that

**Comment by ORP967** [comment]
I have a working miner that uses the current "getworktemplate" in python 3. It is a code from (https://github.com/vsergeev) that I changed to check for a new block every 20 sc or so and start mining again every time a new block is detected. Currently getting 1.01KH/s on a Dell.
