### ISSUE TITLE
is it on

### ISSUE THREAD

**Issue by appledevpro** [jgarzik/pyminer#27]
When I run the code all it says is Usage: pyminer.py CONFIG-FILE. Do I just leave it open and does it just work like that.

**Comment by halwarsing** [comment]
Create an example.cfg file and run the script with this command: python pyminer.py example.cfg

**Comment by appledevpro** [comment]
before or after the script

**Comment by appledevpro** [comment]
still not working

**Comment by appledevpro** [comment]
im using rep.it, is there a recomended way to run the code

**Comment by halwarsing** [comment]
write in console this command: python pyminer.py yourconfig.cfg

**Comment by appledevpro** [comment]
thanks

**Comment by appledevpro** [comment]
still doesnt work

https://user-images.githubusercontent.com/75698279/103916443-6e62e680-50da-11eb-993e-56a91897aa58.mp4

**Comment by muzafarali** [comment]
Hi,
how we get username and password for RPC?

**Comment by appledevpro** [comment]
same problem

**Comment by ORP967** [comment]
I have a working miner that uses the current "getworktemplate" in python 3. It is a code from (https://github.com/vsergeev) that I changed to check for a new block every 20 sc or so and start mining again every time a new block is detected. Currently getting 1.01KH/s on a Dell.
