### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [jgarzik/pyminer#34]
(Traceback):
```
line 179, in loop
    rpc = BitcoinRPC(settings['host'], settings['port'],
KeyError: 'host'
4 mining threads started
Wed Jul 28 22:12:43 2021 Miner Starts - 193.29.105.150:3333
Wed Jul 28 22:12:43 2021 Miner Stops - 193.29.105.150:3333
```

config.cfg
```
#
# RPC login details
#
host=193.29.105.150
port=3333

rpcuser=Erik_V7
rpcpass=anything


#
# mining details
#

threads=4

# periodic rate for requesting new work, if solution not found
scantime=60


#
# misc.
#

# not really used right now
logdir=/tmp/pyminer

# set to 1, to enable hashmeter output
hashmeter=0
```

**Comment by iamdiwang** [comment]
The script is built on python2 , you probably run the script on python3 environment , go download and install python2 and run the script on python2 environment

**Comment by ORP967** [comment]
I have a working miner that uses the current "getworktemplate" in python 3. It is a code from (https://github.com/vsergeev) that I changed to check for a new block every 20 sc or so and start mining again every time a new block is detected. Currently getting 1.01KH/s on a Dell.
